name: congestion-map
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - flask=2.2.3
  - flask-cors=3.0.10
  - pandas=1.5.3
  - numpy=1.24.2
  - requests=2.28.2
  - pip=22.3.1
  - pip:
    - python-dotenv==1.0.0